### ISSUE TITLE
Use aria described-by for each form field’s help text

### ISSUE THREAD

**Issue by fofr** [DFE-Digital/manage-courses-ui#155]
Example:

For "About this course", the leading text needs to be marked up so that it describes the field.

![screen shot 2018-09-03 at 14 31 53](https://user-images.githubusercontent.com/319055/44989567-2f5e7c80-af86-11e8-8899-d13024e9d7a7.png)

**Comment by the-daniel-rothig** [comment]
recreated on trello

**Comment by dankmitchell** [comment]
Solved in https://github.com/DFE-Digital/manage-courses-ui/pull/224
