### ISSUE TITLE
Tweaks to usability of copy courses

### ISSUE THREAD

**Issue by fofr** [DFE-Digital/manage-courses-ui#164]
Copy courses was designed as frontend enhancement but we've been able to build it using the backend. This changes the behaviour slightly and we need to tweak the design accordingly.

## Move the success message and change the messaging

Now there's a full page reload we need to:
* clarify that this copied content is not yet saved – with copy and orange colour (eg "draft", hypothesis: success would give false indication of save state)
* move the "Fields copied" text from the right to the top to be consistent and prominent
* link to each field copied (like we would with an error – this could come as an enhancement later)

Old: 
![screen shot 2018-09-04 at 11 32 48](https://user-images.githubusercontent.com/319055/45026473-46f53e00-b036-11e8-9c5d-22d7b9ad46c5.png)

New:
![screen shot 2018-09-04 at 11 41 14](https://user-images.githubusercontent.com/319055/45026849-7a849800-b037-11e8-8b36-6a9e096e945e.png)

## Javascript warnings

If the user tries to copy content but some boxes already contain text, we need to warn them that this text may be overwritten.

If the user tries to leave the pages after copying content but without saving, we need to warn about unsaved changes (eg marking the form as dirty)

**Comment by fofr** [comment]
Error state:

![screen shot 2018-09-04 at 12 28 54](https://user-images.githubusercontent.com/319055/45028751-20d39c00-b03e-11e8-8847-b4a9acdb3884.png)

**Comment by the-daniel-rothig** [comment]
"Move the success message and change the messaging" done
