### ISSUE TITLE
Fix "1 courses" on organisations list

### ISSUE THREAD

**Issue by fofr** [DFE-Digital/manage-courses-ui#171]
![screen shot 2018-09-04 at 14 04 12](https://user-images.githubusercontent.com/319055/45033101-6c407700-b04b-11e8-8849-883af31722e4.png)

1 course. Not 1 courses.

**Comment by dankmitchell** [comment]
This was fixed as part of https://github.com/DFE-Digital/manage-courses-ui/pull/169

**Comment by benilovj** [comment]
@dankmitchell I'm not convinced this is fixed... still seeing this on Dev:

![image](https://user-images.githubusercontent.com/23801/45088094-ef230980-b0ff-11e8-9eff-095bf4219f08.png)
