### ISSUE TITLE
Minor: Bad error message when entering something that is not a number in a fee field

### ISSUE THREAD

**Issue by fofr** [DFE-Digital/manage-courses-ui#173]
"FeeUkEu" and "FeeInternational" is not user friendly.

This will only happen if a platform allows a non-numeric input for `input type="number"` fields.

![screen shot 2018-09-04 at 14 41 39](https://user-images.githubusercontent.com/319055/45034968-c42dac80-b050-11e8-9ad7-aef4cbe60517.png)

**Comment by dankmitchell** [comment]
Pretty sure we fixed this in https://github.com/DFE-Digital/manage-courses-ui/pull/179
