### ISSUE TITLE
Persist validation when publishing

### ISSUE THREAD

**Issue by fofr** [DFE-Digital/manage-courses-ui#199]
When a user publishes and validation fails, we show an error summary on the course page. These errors click through to the child pages; eg if "How school placements work" field is missing, an error shows and it clicks through to the "How school placements work" section on the "About this course" page.

When a user clicks through to one of the child pages, the validation errors need to still show.

The page should have:
* a summary at the top of the child page
* the summary lists all the errors on the page, not just the one clicked
* clicking each error scrolls the page down
* fields with an error are highlighted red

More details here:
https://manage-courses-prototype.herokuapp.com/history/validating-on-publish#validating-about-this-course

https://trello.com/c/CGAEkWMw/301-persist-validation-when-publishing

**Comment by dankmitchell** [comment]
This isn't trivial and as its in the Trello icebox already i'll leave Jake to prioritise it.

**Comment by tvararu** [comment]
Fixed in manage-courses-frontend ✔️
