### ISSUE TITLE
Missing image assets

### ISSUE THREAD

**Issue by fofr** [DFE-Digital/manage-courses-ui#41]
It looks like we aren't pulling in some of the images from GOVUK Elements. There should be an arrow image between these two links to indicate it's a breadcrumb:

![screen shot 2018-06-28 at 09 30 18](https://user-images.githubusercontent.com/319055/42022806-19dd5b9c-7ab6-11e8-8c7b-e4d67efa350d.png)

**Comment by defong** [comment]
Just so you aware that breadcrumb is gone

**Comment by dankmitchell** [comment]
Fixed on https://github.com/DFE-Digital/manage-courses-ui/pull/72
