### ISSUE TITLE
URLs should be dashed and lowercase

### ISSUE THREAD

**Issue by fofr** [DFE-Digital/manage-courses-ui#47]
Can course URLs be tweaked a bit? At the moment they are not lowercase and can contain spaces:
`/course/G56/Art%20and%20Design/2HCD`

See also https://www.gov.uk/guidance/content-design/url-standards-for-gov-uk

**Comment by dankmitchell** [comment]
Done https://github.com/DFE-Digital/manage-courses-ui/commit/7877f9236731f8b27cee8b6d4150c458c103c7ce
